// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns service health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.healthResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "delete": {
                "description": "Clears the current database-backed session cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthErrorResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "description": "Returns the authenticated user's profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/user.UserErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user.UserErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates provided profile fields for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update current user",
                "parameters": [
                    {
                        "description": "Profile update payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateMeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.MeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/user.UserErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/user.UserErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/user.UserErrorResponse"
                        }
                    }
                }
            }
        },
        "/signin": {
            "post": {
                "description": "Authenticates a user with e-mail and password and sets an HttpOnly database-backed session cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign in",
                "parameters": [
                    {
                        "description": "Signin payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SigninRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthErrorResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "Registers a user with e-mail and password and sets an HttpOnly database-backed session cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "Signup payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthErrorResponse"
                        }
                    }
                }
            }
        },
        "/tracks": {
            "get": {
                "description": "Returns tracks owned by the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracks"
                ],
                "summary": "List tracks",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum tracks to return. Defaults to 20 and is capped at 100.",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque cursor returned by a previous list response.",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "draft",
                            "uploading",
                            "processing",
                            "ready",
                            "failed"
                        ],
                        "type": "string",
                        "description": "Track status filter. Soft-deleted tracks are not returned.",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "private",
                            "unlisted",
                            "public"
                        ],
                        "type": "string",
                        "description": "Track visibility filter.",
                        "name": "visibility",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/track.TracksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/track.TrackErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/track.TrackErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/track.TrackErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.AuthErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "authentication required"
                },
                "status": {
                    "type": "string",
                    "example": "failure"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "auth.AuthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.AuthResponseData"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "auth.AuthResponseData": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/auth.AuthSessionResponse"
                },
                "user": {
                    "$ref": "#/definitions/auth.AuthUserResponse"
                }
            }
        },
        "auth.AuthSessionResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                }
            }
        },
        "auth.AuthUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "usr_abc123"
                },
                "name": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "auth.LogoutResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.LogoutResponseData"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "auth.LogoutResponseData": {
            "type": "object"
        },
        "auth.SigninRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "example": "P@ssw0rd1"
                }
            }
        },
        "auth.SignupRequest": {
            "type": "object",
            "required": [
                "confirm_password",
                "email",
                "password"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string",
                    "example": "P@ssw0rd1"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8,
                    "example": "P@ssw0rd1"
                }
            }
        },
        "server.healthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/server.healthResponseData"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "server.healthResponseData": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "music-player"
                }
            }
        },
        "track.Status": {
            "type": "string",
            "enum": [
                "draft",
                "uploading",
                "processing",
                "ready",
                "failed",
                "deleted"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusUploading",
                "StatusProcessing",
                "StatusReady",
                "StatusFailed",
                "StatusDeleted"
            ]
        },
        "track.TrackErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "authentication required"
                },
                "status": {
                    "type": "string",
                    "example": "failure"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "track.TrackPaginationResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean",
                    "example": false
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "next_cursor": {
                    "type": "string",
                    "example": "eyJjcmVhdGVkX2F0IjoiMjAyNi0wNi0xMVQxMjowMDowMFoiLCJpZCI6InRya18xMjMifQ"
                }
            }
        },
        "track.TrackResponse": {
            "type": "object",
            "properties": {
                "album": {
                    "type": "string",
                    "example": "Album title"
                },
                "artist": {
                    "type": "string",
                    "example": "Artist name"
                },
                "created_at": {
                    "type": "string"
                },
                "disc_number": {
                    "type": "integer",
                    "example": 1
                },
                "duration_ms": {
                    "type": "integer",
                    "example": 180000
                },
                "explicit": {
                    "type": "boolean",
                    "example": false
                },
                "genre": {
                    "type": "string",
                    "example": "electronic"
                },
                "id": {
                    "type": "string",
                    "example": "trk_abc123"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "release_year": {
                    "type": "integer",
                    "example": 2026
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/track.Status"
                        }
                    ],
                    "example": "draft"
                },
                "title": {
                    "type": "string",
                    "example": "Song title"
                },
                "track_number": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string"
                },
                "visibility": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/track.Visibility"
                        }
                    ],
                    "example": "private"
                }
            }
        },
        "track.TracksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/track.TracksResponseData"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "track.TracksResponseData": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/track.TrackPaginationResponse"
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/track.TrackResponse"
                    }
                }
            }
        },
        "track.Visibility": {
            "type": "string",
            "enum": [
                "private",
                "unlisted",
                "public"
            ],
            "x-enum-varnames": [
                "VisibilityPrivate",
                "VisibilityUnlisted",
                "VisibilityPublic"
            ]
        },
        "user.MeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.MeResponseData"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "user.MeResponseData": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/user.UserResponse"
                }
            }
        },
        "user.UpdateMeRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "name": {
                    "type": "string",
                    "example": "New display name"
                }
            }
        },
        "user.UserErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "authentication required"
                },
                "status": {
                    "type": "string",
                    "example": "failure"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "user.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "usr_abc123"
                },
                "image": {
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "name": {
                    "type": "string",
                    "example": "user"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Music Box Backend API",
	Description:      "Backend service for the Music Box project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
